name: Node Setup Dependencies
Description: Running Echo

runs:
  using: "composite"
  steps:
    - name: Install Node Dependencies
      run: |
        cd client
        yarn install --frozen-lockfile
      shell: bash
