name: Node Setup Dependencies
Description: Running Echo

runs:
  install-node-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node Dependencies
        run: cd client && yarn install --frozen-lockfile
