name: Node Setup Dependencies
Description: Running Echo

runs:
  using: "composite"
  steps:
    - name: Install Node Dependencies
      run: |
        cd client
        yarn install --frozen-lockfile
      shell: bash

    - name: Install Fusion CLI
      run: |
        npm i -g @equinor/fusion-framework-cli
      shell: bash

    - name: Install App Deps
      run: |
        cd client/apps/portal-administration
        yarn install
      shell: bash
