apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: pcs5-demo
spec:
  build:
    useBuildKit: true
    useBuildCache: true
  environments:
    - name: test
      build:
        from: feat/pcs5-radix
  components:
    # Web Server - Admin
    - name: admin
      identity:
        azure:
          clientId: ea425507-0de4-4f5f-bac8-48cea54f7a0c
      src: . # Dockerfile location
      dockerfileName: clientBackend.Dockerfile
      variables:
        ASPNETCORE_URLS: "http://*:5000"
        ApplicationInsights__ConnectionString: ""
        AzureAd__ClientId: ""
        ClientBundle__Msal__ClientId: ""
        ClientBundle__PortalId: ""
        FusionPortalApi__BaseAddress: ""
        FusionPortalApi__Scope: ""
        AssetProxy__FusionPortalUrl: ""
        AssetProxy__FusionPeopleUrl: ""
        AssetProxy__FusionAppsUrl: ""
        AssetProxy__TokenScope: ""
        FusionProjectPortalApi__BaseAddress: ""
        FusionProjectPortalApi__Scope: ""
        FusionBookmarks__Name: ""
        FusionBookmarks__Identifier: ""
        FusionBookmarks__Subsystem: "Project Portal"
        ClientBundle__FusionLegacyEnvIdentifier: "ci"
      ports:
        - name: http
          port: 5000
      publicPort: http
      environmentConfig:
        - environment: test
          identity:
            azure:
              clientId: 68e0c697-b713-4cd0-b24f-c2509f442e84
          secretRefs:
            azureKeyVaults:
              - name: kv-pep-ws-noe-test
                path: /mnt/key-vault
                useAzureIdentity: true
                items:
                  - name: AzureAd--ClientSecret
                    type: secret
                    envVar: AzureAd__ClientSecret
                  - name: ClientBundle--AgGrid--LicenseKey
                    type: secret
                    envVar: ClientBundle__AgGrid__LicenseKey
          replicas: 1
          monitoring: true
          resources:
            requests:
              memory: "2048Mi"
              cpu: "800m"
            limits:
              memory: "2048Mi"
              cpu: "800m"

    # Web Server - Transfer
    - name: transfer
      identity:
        azure:
          clientId: ea425507-0de4-4f5f-bac8-48cea54f7a0c
      src: . # Dockerfile location
      dockerfileName: clientBackend.Dockerfile
      variables:
        ASPNETCORE_URLS: "http://*:5000"
        ApplicationInsights__ConnectionString: ""
        AzureAd__ClientId: ""
        ClientBundle__Msal__ClientId: ""
        ClientBundle__PortalId: ""
        FusionPortalApi__BaseAddress: ""
        FusionPortalApi__Scope: ""
        AssetProxy__FusionPortalUrl: ""
        AssetProxy__FusionPeopleUrl: ""
        AssetProxy__FusionAppsUrl: ""
        AssetProxy__TokenScope: ""
        FusionProjectPortalApi__BaseAddress: ""
        FusionProjectPortalApi__Scope: ""
        FusionBookmarks__Name: ""
        FusionBookmarks__Identifier: ""
        FusionBookmarks__Subsystem: "Project Portal"
        ClientBundle__FusionLegacyEnvIdentifier: "ci"
      ports:
        - name: http
          port: 5000
      publicPort: http
      environmentConfig:
        - environment: test
          identity:
            azure:
              clientId: 68e0c697-b713-4cd0-b24f-c2509f442e84
          secretRefs:
            azureKeyVaults:
              - name: kv-pep-ws-noe-test
                path: /mnt/key-vault
                useAzureIdentity: true
                items:
                  - name: AzureAd--ClientSecret
                    type: secret
                    envVar: AzureAd__ClientSecret
                  - name: ClientBundle--AgGrid--LicenseKey
                    type: secret
                    envVar: ClientBundle__AgGrid__LicenseKey
          replicas: 1
          monitoring: true
          resources:
            requests:
              memory: "2048Mi"
              cpu: "800m"
            limits:
              memory: "2048Mi"
              cpu: "800m"

    # Web Server - Scoping
    - name: scoping
      identity:
        azure:
          clientId: ea425507-0de4-4f5f-bac8-48cea54f7a0c
      src: . # Dockerfile location
      dockerfileName: clientBackend.Dockerfile
      variables:
        ASPNETCORE_URLS: "http://*:5000"
        ApplicationInsights__ConnectionString: ""
        AzureAd__ClientId: ""
        ClientBundle__Msal__ClientId: ""
        ClientBundle__PortalId: ""
        FusionPortalApi__BaseAddress: ""
        FusionPortalApi__Scope: ""
        AssetProxy__FusionPortalUrl: ""
        AssetProxy__FusionPeopleUrl: ""
        AssetProxy__FusionAppsUrl: ""
        AssetProxy__TokenScope: ""
        FusionProjectPortalApi__BaseAddress: ""
        FusionProjectPortalApi__Scope: ""
        FusionBookmarks__Name: ""
        FusionBookmarks__Identifier: ""
        FusionBookmarks__Subsystem: "Project Portal"
        ClientBundle__FusionLegacyEnvIdentifier: "ci"
      ports:
        - name: http
          port: 5000
      publicPort: http
      environmentConfig:
        - environment: test
          identity:
            azure:
              clientId: 68e0c697-b713-4cd0-b24f-c2509f442e84
          secretRefs:
            azureKeyVaults:
              - name: kv-pep-ws-noe-test
                path: /mnt/key-vault
                useAzureIdentity: true
                items:
                  - name: AzureAd--ClientSecret
                    type: secret
                    envVar: AzureAd__ClientSecret
                  - name: ClientBundle--AgGrid--LicenseKey
                    type: secret
                    envVar: ClientBundle__AgGrid__LicenseKey
          replicas: 1
          monitoring: true
          resources:
            requests:
              memory: "2048Mi"
              cpu: "800m"
            limits:
              memory: "2048Mi"
              cpu: "800m"

    # Web Server - Status
    - name: status
      identity:
        azure:
          clientId: ea425507-0de4-4f5f-bac8-48cea54f7a0c
      src: . # Dockerfile location
      dockerfileName: clientBackend.Dockerfile
      variables:
        ASPNETCORE_URLS: "http://*:5000"
        ApplicationInsights__ConnectionString: ""
        AzureAd__ClientId: ""
        ClientBundle__Msal__ClientId: ""
        ClientBundle__PortalId: ""
        FusionPortalApi__BaseAddress: ""
        FusionPortalApi__Scope: ""
        AssetProxy__FusionPortalUrl: ""
        AssetProxy__FusionPeopleUrl: ""
        AssetProxy__FusionAppsUrl: ""
        AssetProxy__TokenScope: ""
        FusionProjectPortalApi__BaseAddress: ""
        FusionProjectPortalApi__Scope: ""
        FusionBookmarks__Name: ""
        FusionBookmarks__Identifier: ""
        FusionBookmarks__Subsystem: "Project Portal"
        ClientBundle__FusionLegacyEnvIdentifier: "ci"
      ports:
        - name: http
          port: 5000
      publicPort: http
      environmentConfig:
        - environment: test
          identity:
            azure:
              clientId: 68e0c697-b713-4cd0-b24f-c2509f442e84
          secretRefs:
            azureKeyVaults:
              - name: kv-pep-ws-noe-test
                path: /mnt/key-vault
                useAzureIdentity: true
                items:
                  - name: AzureAd--ClientSecret
                    type: secret
                    envVar: AzureAd__ClientSecret
                  - name: ClientBundle--AgGrid--LicenseKey
                    type: secret
                    envVar: ClientBundle__AgGrid__LicenseKey
          replicas: 1
          monitoring: true
          resources:
            requests:
              memory: "2048Mi"
              cpu: "800m"
            limits:
              memory: "2048Mi"
              cpu: "800m"