name: Snyk .net
description: Security Snyk scan on dotnet

run:
  security:   
    steps:     
      
      - name: Run Snyk on dotnet
        uses: snyk/actions/dotnet@master
        continue-on-error: true 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --severity-threshold=medium

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
