name: Size Labeler

inputs:
  token:
    required: true

run:
  name: "Label the PR"
  steps:
    - name: Pull request size labelling
      uses: alexromer0/pull-request-labeler@2.1.1
      with:
        GITHUB_TOKEN: "${{ inputs.token }}"
        xs_limit: "50"
        sm_limit: "100"
        md_limit: "300"
        lg_limit: "600"
