# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler

inputs:
  token:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ inputs.token }}"
        sync-labels: true

    - name: Pull request size labelling
      uses: alexromer0/pull-request-labeler@2.1.1
      with:
        GITHUB_TOKEN: "${{ inputs.token }}"
        xs_limit: "50"
        sm_limit: "100"
        md_limit: "300"
        lg_limit: "600"
