name: Lint Web Client
description: Run es lint on the web client code

runs:
  eslint:
    - name: Lint Project
      if: ${{ github.actor != 'dependabot[bot]' }}
      run: cd client  && yarn lint --max-warnings 0;

    - name: Annotate Code Linting Results
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: ataylorme/eslint-annotate-action@1.1.2
      continue-on-error: true
      with:
        repo-token: "${{ github.token }}"
        report-json: "eslint-report.log.json"

    - name: Upload ESLint report
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: eslint-report.log.json
        path: eslint-report.log.json
