name: Node Setup
description: Runs Setup Node with the provided matrix versions

runs:
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
        cache: "yarn"
