name: Node Setup
description: Running node setup on provided versions

inputs:
  versions:
    description: "node versions to run"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.versions }}
        cache: "yarn"
