name: Node Setup
description: Runs Setup Node with the provided matrix versions

inputs:
  node-version:
    description: "Node version to run"
    required: true

runs:
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"
