name: Backend Api Pull-request

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
    types:
      - opened
      - edited
      - synchronize

jobs:
  echo:
    name: Version or publish packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Labler
        uses: ./.github/actions/labler

      - name: Size Labler
        uses: ./.github/actions/size-labler

      - name: Post Pull Request
        uses: ./.github/actions/post-pull-request
