name: Backend Api Pull-request

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
    types:
      - opened
      - edited
      - synchronize

jobs:
  echo:
    name: Version or publish packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
