name: Backend Api Pull-request

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
    types:
      - opened
      - edited
      - synchronize

jobs:
  echo:
    name: Backend pr job
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dotnet build
        shell: bash
        run: dotnet build ./backend/src/Equinor.ProjectExecutionPortal.sln

      - name: Dotnet test
        shell: bash
        run: dotnet test ./backend/src/Equinor.ProjectExecutionPortal.sln
