name: Web Client

on:
  pull_request:
    branches:
      - main
    paths:
      - "client/**"
    types: [opened, synchronize]

jobs:
  web-client-pr:
    name: Open Pull Request
    strategy:
      matrix:
        version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/node-setup
        with:
          versions: ${{ matrix.version }}

      - name: Install Dependecies
        uses: ./.github/actions/install-dependencies

      - name: Client Build
        uses: ./.github/actions/client-build

      - name: Client Test
        uses: ./.github/actions/client-test

      - name: Es Lint
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: ./.github/actions/es-lint
