name: Get PR description

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  print_title_of_pr:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}

      - name: Create changeset
        id: create-changeset
        uses: ./.github/actions/create-changeset
        with:
          projectName: "fusion-porject-portal"


      - name: Commit Changeset 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{steps.create-changeset.outputs.changeSetPath}}
          branch: ${{ github.head_ref }}
