name: TEst

on:
  workflow_dispatch:

jobs:
  web-client-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check Changed Files
        run: |
          if git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep -q "^/client/apps/"; then
            echo "Files in client/apps/ have changed"
          else
            echo "No files in client/apps/ have changed"
          fi
