name: Check Changes in client/apps

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: git fetch origin

      - name: Check for changes in /client/apps
        id: check_changes
        run: |
          # Check for changes in the /client/apps folder
          if git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep -q "^client/apps/"; then
            echo "Changes detected in client/apps/"
            echo "::set-output name=changes_detected::true"
          else
            echo "No changes detected in client/apps/"
            echo "::set-output name=changes_detected::false"
          fi

      - name: Output result
        run: echo "Changes in client/apps: ${{ steps.check_changes.outputs.changes_detected }}"
