name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - feat/portal-administration

jobs:
  web-client-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check Changed Files
        run: |
          if git diff --no-index --name-only ${{ github.ref }}...${{ github.head_ref }} | grep -q "^client/apps/"; then
          echo "Files in client/apps/ have changed"
          else
          echo "No files in client/apps/ have changed"
          fi
          echo "Current branch: ${{ github.ref }}"
          echo "Base branch: ${{ github.base_ref }}"
